// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gorm.io/gorm"
	"impirrot/internal/adhoc/biz"
	"impirrot/internal/adhoc/dal"
	"impirrot/internal/adhoc/service"
	"impirrot/internal/shared/auth"
)

// Injectors from wire.go:

// InitializeAdhocService 初始化 Adhoc 服务的所有依赖
func InitializeAdhocService(db *gorm.DB) (*AdhocComponents, error) {
	adhocDALInterface := dal.NewAdhocDAL(db)
	adhocBizInterface := biz.NewAdhocBiz(adhocDALInterface)
	adhocServiceInterface := service.NewAdhocServiceImpl(adhocBizInterface)
	authClient := auth.NewAuthClient()
	permissionChecker := auth.NewPermissionChecker(authClient)
	adhocComponents := NewAdhocComponents(adhocServiceInterface, permissionChecker)
	return adhocComponents, nil
}
