// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gorm.io/gorm"
	"impirrot/internal/api/biz"
	"impirrot/internal/api/dal"
	"impirrot/internal/api/handler"
	"impirrot/internal/shared/auth"
)

// Injectors from wire.go:

// InitializeAPIService 初始化 API 服务的所有依赖
func InitializeAPIService(db *gorm.DB) (*APIComponents, error) {
	userDALInterface := dal.NewUserDAL(db)
	helloServiceInterface := biz.NewHelloService(userDALInterface)
	helloHandlerInterface := handler.NewHelloHandler(helloServiceInterface)
	authClient := auth.NewAuthClient()
	permissionChecker := auth.NewPermissionChecker(authClient)
	apiComponents := NewAPIComponents(helloHandlerInterface, permissionChecker)
	return apiComponents, nil
}
